### ISSUE TITLE
Получил письма, которые не должен был получить

### ISSUE THREAD

**Issue by kirilldudinsky** [schaman/mx#11]
Может я что-то не так сделал

Я заказал вебинар «Как заработать 60 000 р.» - продукт 8 - [оффер](http://money.prorealnost.com/admin/offer/16)

Подтвердил рассылку

Пришло письмо со ссылкой на вебинар. А потом еще два письма из соседнего Maling List'a

![2014-12-14 7 31 29](https://cloud.githubusercontent.com/assets/9354450/5426641/5a14ef48-8363-11e4-8f42-46963c29368f.png)

![2014-12-14 7 35 01](https://cloud.githubusercontent.com/assets/9354450/5426652/d1e7243c-8363-11e4-8a3e-67d3896378b3.png)

**Comment by kirilldudinsky** [comment]
![2014-12-15 3 45 56](https://cloud.githubusercontent.com/assets/9354450/5430298/36241c62-840d-11e4-99b4-bbcab7139862.png)

**Comment by schaman** [comment]
fixed
