### ISSUE TITLE
Не получается добавить письмо

### ISSUE THREAD

**Issue by kirilldudinsky** [schaman/mx#18]
Вот [тут](http://mx.icoach.io/admin/list/newsletter/15)

![2015-01-06 3 19 12](https://cloud.githubusercontent.com/assets/9354450/5623354/eb852f32-9552-11e4-8fe0-0f246587d58e.png)

Нажимаю Save и все...

![2015-01-06 3 19 50](https://cloud.githubusercontent.com/assets/9354450/5623355/eb886b34-9552-11e4-9942-e4321137431e.png)

**Comment by schaman** [comment]
fixed
