### ISSUE TITLE
Что-то работает не так

### ISSUE THREAD

**Issue by kirilldudinsky** [schaman/mx#19]
Почему-то создалось 3 копии письма и ни в одно не могу зайти для редактирования

[Лист 1](http://mx.icoach.io/admin/list/1)

![2015-01-06 4 56 47](https://cloud.githubusercontent.com/assets/9354450/5624132/97d03f54-9560-11e4-9cd2-4c82ae868cc1.png)

Захожу в [письмо 16](http://mx.icoach.io/admin/list/newsletter/16)

![2015-01-06 4 58 15](https://cloud.githubusercontent.com/assets/9354450/5624141/abba6198-9560-11e4-8bb5-33460ed194ab.png)

В [письме 15](http://mx.icoach.io/admin/list/newsletter/15) то же самое

**Comment by schaman** [comment]
не ошибка
