### ISSUE TITLE
Хочу при оплате продукта автоматический перенос емейла из одного списка в другой

### ISSUE THREAD

**Issue by kirilldudinsky** [schaman/mx#21]
Для того, чтобы формировать список клиентов и делать им спец предложения в дальнейшем.

Пример:

Человек захотел скачать бесплатный продукт «11 бизнес-секретов...» ([флоу](http://money.prorealnost.com/admin/flow/30))

Он попадает в список [Подписчики Бизнес](http://mx.icoach.io/admin/list/9)

Затем ему приходит авто-рассылка с предложением купить Фундамент бизнеса ([флоу](http://money.prorealnost.com/admin/flow/34))

Я хочу, чтобы после оплаты Фундамента бизнеса человек автоматически удалялся из списка [Подписчики Бизнес](http://mx.icoach.io/admin/list/9) и добавлялся в список [Покупатели Бизнес](http://mx.icoach.io/admin/list/25)

Есть ли сейчас возможность это настроить? Если да, покажи мне, как это делается, и я сделаю это во всех старых и новых потоках. Спасибо!

**Comment by schaman** [comment]
Вот так: http://money.prorealnost.com/admin/flow/39
