### ISSUE TITLE
Хочу разделить нашу базу на подписчиков и клиентов

### ISSUE THREAD

**Issue by kirilldudinsky** [schaman/mx#22]
Для того, чтобы разослать спец предложение о новом тренинге «Продуктивность» только клиентам - т.е. тем, кто у нас уже покупал продукты по данной или смежным тематикам и «реанимировать» старых клиентов - сделать их постоянными клиентами.
1. Для того, чтобы реанимировать проходивших ПроРеальность, добавь в список [Старые покупатели ПроРеальности](http://mx.icoach.io/admin/list/26) емейлы людей, которые: 
- не зарегистрированы на новом icoach'e  
- проходили Прореальность: ОК и/или ПК и/или Лидерку

2. Для того, чтобы сделать спец предложение старым клиентам:  
Добавь в список [Старые покупатели Личная эффективность](http://mx.icoach.io/admin/list/20) емейлы людей, которые: 
- не зарегистрированы на новом icoach'e и  
- покупали на старом icoach'e [Мотивация, уверенность, харизма](http://icoach.io/author/nickvorobiov/audiocourse/motivatsiya-uverennost-harizma) и/или [Как двигаться к цели не смотря на обстоятельства](http://icoach.io/author/nickvorobiov/videocourse/kak-dvigatsya-k-tseli-nesmotrya-na-obstoyatelstva) и/или [Книгу Как стать богатым...](http://icoach.io/author/nickvorobiov/book/kak-stat-bogatym-i-uspeshnym-ostavayas-tupym-i-lenivym) и/или [Как стать лидером](http://icoach.io/author/nickvorobiov/videocourse/kak-stat-liderom) и/или [Как избавиться от лени](http://icoach.io/author/nickvorobiov/videocourse/kak-izbavitsya-ot-leni)

Добавь в список [Старые покупатели Бизнес](http://mx.icoach.io/admin/list/24) емейлы людей, которых нет на новом icoach'e и которые покупали [Фундамент бизнеса](http://icoach.io/author/nickvorobiov/videocourse/fundament-biznesa-kak-vospitat-sebya-biznesmenom)

3. Для того, чтобы сделать спец предложение текущим клиентам

Напиши мне инструкцию, как мне руками удалить клиента из одного списка в mx'е и добавить в другой (я так и не разобрался). 

Например, некоторые люди заказали тренинг Фундамент бизнеса, но оплатили его не через ic. Я хочу в ручном режиме перенести их из списка [Подписчики Бизнес](http://mx.icoach.io/admin/list/9) в список [Покупатели Бизнес](http://mx.icoach.io/admin/list/25)

**Comment by schaman** [comment]
1. Все зарегистрированы

``` sql
select distinct email from icoach.contact
where id in (select contact_id from icoach.contact_badges)
and email not in (select email from ic.contact)
```

> 0 results

2. Все зарегистрированы

``` sql
select o.email from icoach.orders o
join icoach.package pk on pk.id = o.package_id
join icoach.product p on p.id = pk.product_id
where p.cat_id = 13 and p.author_id = 1
and email not in (select email from ic.contact)
```

> 0 results

3. Все зарегистрированы

``` sql
select o.email from icoach.orders o
join icoach.package pk on pk.id = o.package_id
join icoach.product p on p.id = pk.product_id
where p.cat_id = 15 and p.author_id = 1
and email not in (select email from ic.contact)
```

> 0 results

**Comment by schaman** [comment]
Сначала удаляешь подписчика:
1. Открой подписчика [test@prorealnost.com](http://mx.icoach.io/admin/subscriber/651)
2. Нажми Unsubscribe (он удалится из всех рассылок)

Потом добавляешь заново:
1. Открой новый список [Покупатели Бизнес](http://mx.icoach.io/admin/list/25)
2. Нажми opt-in
3. Введи любое имя (если он уже был подписан, то имя остаётся старым)
4. Введи емейл test@prorealnost.com
5. Нажми кнопку

**Comment by schaman** [comment]
готово
