### ISSUE TITLE
Не работает статистика по кликам в письмах

### ISSUE THREAD

**Issue by kirilldudinsky** [schaman/mx#23]
Почему-то в [этом письме](http://mx.icoach.io/admin/list/newsletter/64) на 200 открытых писем счетчик кликов показывает 0. Очень странно, неужели никто не кликнул? Я предполагаю, что счетчик работает некорректно. Или я делаю что-то не так?

![2015-03-20 22 21 54](https://cloud.githubusercontent.com/assets/9354450/6761100/d50dc99e-cf4f-11e4-8224-700270c87f1b.png)

**Comment by schaman** [comment]
Вот тут ошибка:

```
[**http://money.prorealnost.com/page/produktivnost-video**](http://money.prorealnost.com/page/produktivnost-video?src=prorealnostmail1&m={{m}})
```

Текст ссылки — это URL, а цель ссылки — это другой URL.

Ты пытаешься обмануть пользователя, или ошибся — то есть делаешь вид, что он переходит по одному URL (который в тексте ссылки), а на самом деле он переходит по другому URL (который в цели ссылки).

Почтовые системы видят попытку обмана (или ошибку) и не дают тебе — заменяют цель ссылки (URL с параметрами) на тот URL, который указан в тексте ссылки (без параметров).

Proof:

```
Кликни [сюда](http://money.prorealnost.com/page/produktivnost-video?src=prorealnostmail1&m={{m}}), чтобы посмотреть видео прямо сейчас

[**http://money.prorealnost.com/page/produktivnost-video**](http://money.prorealnost.com/page/produktivnost-video?src=prorealnostmail1&m={{m}})
```

Здесь первая ссылка ("сюда") работает правильно (увеличивает счётчик Opens), а вторая — не работает (переходит по ссылке без параметров, и поэтому счётчик не увеличивает).
