### ISSUE TITLE
Что-то сломалось в отправке писем

### ISSUE THREAD

**Issue by kirilldudinsky** [schaman/mx#24]
Вот [это письмо](http://mx.icoach.io/admin/list/newsletter/77) должно было быть отправлено 27 марта, а до сих пор висит в pending'е

![2015-03-29 8 23 34](https://cloud.githubusercontent.com/assets/9354450/6884329/f4bd1a08-d5ec-11e4-8be3-9ead579263bc.png)

Кроме того, в [этом списке](http://mx.icoach.io/admin/list/newsletter/77) 108 писем висит в pending'е, что очень странно.

![2015-03-29 8 24 52](https://cloud.githubusercontent.com/assets/9354450/6884331/16d4bcfe-d5ed-11e4-81c3-c4e50a7860e3.png)

**Comment by schaman** [comment]
Я перезапустил процесс, отправляющий письма, и всё сразу отправилось. Не знаю, что сломалось. Поглядывай, пожалуйста, чтобы всё вовремя уходило в ближайшее время, и если что — сразу пиши.
