### ISSUE TITLE
Проверить, что все письма отправляются

### ISSUE THREAD

**Issue by kirilldudinsky** [schaman/mx#9]
Я писал в [тасках](http://tech.icoach.io/task/704), решил тут продублировать

Есть подозрение, что второе письмо [73% людей](http://mx.icoach.io/admin/list/chain/2) было успешно отправлено, а следующее третье письмо [Как избавиться от привычки](http://mx.icoach.io/admin/list/chain/3), которое должно было быть отправлено 02.11, будет отправлено 03.11. 

Может быть delay считается не от даты регистрации, а от даты отправления крайнего письма?

**Comment by schaman** [comment]
проверено, отправляются
